version: '3'
services:
    db:
        build:
            context: .
            dockerfile: Dockerfile-mysql
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-superSecretPassword}
    web-app:
        links:
            - db:db
        build: 
            context: .
            dockerfile: Dockerfile-web-app
        volumes:
            - ./src:/usr/src/app/src/
        ports:
            - ${WEB_APP_PORT:-1337}:1337
volumes:
    db_data:
